version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
  spring-boot-app:
    build:
      dockerfile: ./Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/test

networks:
  backend: